name: Delete merged branch of the backport PRs
on: 
  pull_request:
    types:
      - closed
  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.repo.full_name, 'peterzhuamazon/documentation-website')
    steps:
      - name: Echo remove branch
        run: echo Removing ${{github.event.pull_request.head.ref}}
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
