name: Publish Documentation Website
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  site-publish:
    uses: ./.github/workflows/jekyll-deploy.yml
